# TCL File Generated by Component Editor 16.0.2
# Thu Sep 01 16:54:08 EDT 2016
# DO NOT MODIFY


# 
# freeze_ctl "freeze_ctl" v1.0
#  2016.09.01.16:54:08
# 
# 

# 
# request TCL package from ACDS 16.0
# 
package require -exact qsys 16.0


# 
# module freeze_ctl
# 
set_module_property DESCRIPTION "Contains register to generate freeze signal"
set_module_property NAME freeze_ctl
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "NCL Custom OpenCL Components"
set_module_property AUTHOR "canhld"
set_module_property DISPLAY_NAME "FREEZE CONTROLLER"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL freeze_ctl
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file freeze_ctl.v VERILOG PATH freeze_ctl.v TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter WIDTH INTEGER 32
set_parameter_property WIDTH DEFAULT_VALUE 32
set_parameter_property WIDTH DISPLAY_NAME WIDTH
set_parameter_property WIDTH TYPE INTEGER
set_parameter_property WIDTH UNITS None
set_parameter_property WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property WIDTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point slave
# 
add_interface slave avalon end
set_interface_property slave addressUnits WORDS
set_interface_property slave associatedClock clock
set_interface_property slave associatedReset reset_sink
set_interface_property slave bitsPerSymbol 8
set_interface_property slave bridgedAddressOffset ""
set_interface_property slave bridgesToMaster ""
set_interface_property slave burstOnBurstBoundariesOnly false
set_interface_property slave burstcountUnits WORDS
set_interface_property slave explicitAddressSpan 0
set_interface_property slave holdTime 0
set_interface_property slave linewrapBursts false
set_interface_property slave maximumPendingReadTransactions 1
set_interface_property slave maximumPendingWriteTransactions 0
set_interface_property slave readLatency 0
set_interface_property slave readWaitTime 1
set_interface_property slave setupTime 0
set_interface_property slave timingUnits Cycles
set_interface_property slave transparentBridge false
set_interface_property slave writeWaitTime 0
set_interface_property slave ENABLED true
set_interface_property slave EXPORT_OF ""
set_interface_property slave PORT_NAME_MAP ""
set_interface_property slave CMSIS_SVD_VARIABLES ""
set_interface_property slave SVD_ADDRESS_GROUP ""

add_interface_port slave slave_address address Input 2
add_interface_port slave slave_writedata writedata Input WIDTH
add_interface_port slave slave_read read Input 1
add_interface_port slave slave_write write Input 1
add_interface_port slave slave_byteenable byteenable Input WIDTH/8
add_interface_port slave slave_readdata readdata Output WIDTH
add_interface_port slave slave_readdatavalid readdatavalid Output 1
add_interface_port slave slave_waitrequest waitrequest Output 1
set_interface_assignment slave embeddedsw.configuration.isFlash 0
set_interface_assignment slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink resetn reset_n Input 1


# 
# connection point freeze
# 
add_interface freeze conduit end
set_interface_property freeze associatedClock ""
set_interface_property freeze associatedReset ""
set_interface_property freeze ENABLED true
set_interface_property freeze EXPORT_OF ""
set_interface_property freeze PORT_NAME_MAP ""
set_interface_property freeze CMSIS_SVD_VARIABLES ""
set_interface_property freeze SVD_ADDRESS_GROUP ""

add_interface_port freeze freeze freeze Output 1

add_interface freeze_1 conduit end
set_interface_property freeze_1 associatedClock ""
set_interface_property freeze_1 associatedReset ""
set_interface_property freeze_1 ENABLED true
set_interface_property freeze_1 EXPORT_OF ""
set_interface_property freeze_1 PORT_NAME_MAP ""
set_interface_property freeze_1 CMSIS_SVD_VARIABLES ""
set_interface_property freeze_1 SVD_ADDRESS_GROUP ""
add_interface_port freeze_1 freeze_1 freeze_1 Output 1

add_interface freeze_2 conduit end
set_interface_property freeze_2 associatedClock ""
set_interface_property freeze_2 associatedReset ""
set_interface_property freeze_2 ENABLED true
set_interface_property freeze_2 EXPORT_OF ""
set_interface_property freeze_2 PORT_NAME_MAP ""
set_interface_property freeze_2 CMSIS_SVD_VARIABLES ""
set_interface_property freeze_2 SVD_ADDRESS_GROUP ""
add_interface_port freeze_2 freeze_2 freeze_2 Output 1

add_interface freeze_3 conduit end
set_interface_property freeze_3 associatedClock ""
set_interface_property freeze_3 associatedReset ""
set_interface_property freeze_3 ENABLED true
set_interface_property freeze_3 EXPORT_OF ""
set_interface_property freeze_3 PORT_NAME_MAP ""
set_interface_property freeze_3 CMSIS_SVD_VARIABLES ""
set_interface_property freeze_3 SVD_ADDRESS_GROUP ""
add_interface_port freeze_3 freeze_3 freeze_3 Output 1

